plugins {
    id 'com.android.application'
}

android {
    namespace 'de.gralheertede.kleiderkammer'
    compileSdk 35

    defaultConfig {
        applicationId 'de.gralheertede.kleiderkammer'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '1.0.1'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.activity:activity:1.10.1'
}
